apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing-demo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: guests
